name: cosmos-minimum
channels:
  - astropy
  - conda-forge
  - defaults
dependencies:
  - astropy
  - attrs
  - babel
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - configparser
  - fontconfig
  - freetype
  - healpy
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - jupyter_core
  - jupyter_highlight_selected_word
  - jupyter_latex_envs
  - jupyter_nbextensions_configurator
  - jupyterthemes
  - matplotlib
  - matplotlib-base
  - mpi
  - mpi4py
  - mpich
  - nbconvert
  - nbformat
  - nb_conda_kernels
  - numpy
  - numpydoc
  - openssl
  - pandas
  - pip
  - python
  - python-dateutil
  - pytz
  - pyyaml
  - requests
  - rise
  - scikit-learn
  - scipy
  - future
